### ISSUE TITLE
RTX 3090 out of memory

### ISSUE THREAD

**Issue by DietmarGrabowski** [abacaj/fine-tune-mistral#3]
Hi, i am running out of memory:
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 732.00 MiB (GPU 0; 24.00 GiB total capacity; 20.62 GiB already allocated; 0 bytes free; 22.68 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.

**Comment by abacaj** [comment]
Hi sounds like you are running on 1 GPU, you should probably look into qlora because this setup requires multiple GPUs or enough vram

**Comment by DietmarGrabowski** [comment]
yes, i missed this. Thank you
